Repository akveo/react-native-ui-kitten, pull requests merged in 2019-04, with the labels that each got.

#335 fix(choice-group): Fix incorrect increment of rkChoice children index
  src/components/choiceGroup/rkChoiceGroup.js
Labels: module:ui

#338 feat(framework): enhancements
  src/framework/ui/button/button.spec.tsx.snap
  src/framework/ui/input/input.spec.tsx.snap
  src/framework/ui/list/list.spec.tsx
  src/framework/ui/list/list.spec.tsx.snap
  src/framework/ui/overflowMenu/overflowMenu.component.tsx
  src/framework/ui/overflowMenu/overflowMenuItem.component.tsx
  src/playground/src/app.component.tsx
Labels: enhancement, needs review, next

#339 refactor(ui): button eva mappings
  src/framework/ui/button/button.component.tsx
  src/framework/ui/button/button.spec.tsx.snap
  src/framework/ui/common/mapping.json
  src/playground/src/app.component.tsx
Labels: module:ui, needs review, next

#344 refactor(ui): apply list mappings
  src/framework/ui/common/mapping.json
  src/framework/ui/list/list.spec.tsx.snap
  src/framework/ui/list/listItem.component.tsx
Labels: module:ui, needs review, next

#345 refactor(ui): apply popover mappings
  src/framework/ui/common/mapping.json
  src/framework/ui/popover/popover.component.tsx
  src/framework/ui/popover/popoverView.component.tsx
  src/playground/src/ui/screen/popover.component.tsx
Labels: module:ui, needs review, next

#348 refactor(ui): apply tooltip mappings
  src/framework/ui/common/mapping.json
  src/framework/ui/tooltip/tooltip.component.tsx
  src/playground/src/ui/screen/tooltip.component.tsx
Labels: module:ui, needs review, next

#350 refactor(ui): apply overflow-menu mappings
  src/framework/ui/common/mapping.json
  src/framework/ui/overflowMenu/overflowMenu.component.tsx
  src/framework/ui/overflowMenu/overflowMenu.spec.tsx
  src/framework/ui/overflowMenu/overflowMenu.spec.tsx.snap
  src/framework/ui/overflowMenu/overflowMenuItem.component.tsx
Labels: module:ui, needs review, next

#347 refactor(ui): apply tab mappings
  src/framework/ui/common/mapping.json
  src/framework/ui/tab/tab.component.tsx
  src/framework/ui/tab/tab.spec.tsx.snap
  src/playground/src/ui/screen/tabView.component.tsx
Labels: module:ui, needs review, next

#351 refactor(ui): button - apply mappings
  src/framework/ui/button/button.component.tsx
  src/framework/ui/button/button.spec.tsx.snap
  src/framework/ui/common/mapping.json
Labels: module:ui, needs review, next

#349 refactor(ui): apply top-navigation mappings
  src/framework/ui/common/mapping.json
  src/framework/ui/index.ts
  src/framework/ui/topNavigation/topNavigation.component.tsx
  src/framework/ui/topNavigation/topNavigation.spec.tsx
  src/framework/ui/topNavigation/topNavigation.spec.tsx.snap
  src/framework/ui/topNavigation/topNavigationAction.component.tsx
  src/framework/ui/topNavigation/type.ts
  src/framework/ui/topNavigationBar/topNavigationBar.component.tsx
  src/framework/ui/topNavigationBar/topNavigationBar.spec.tsx.snap
  src/framework/ui/topNavigationBar/topNavigationBarAction.component.tsx
  src/playground/src/ui/screen/index.ts
  src/playground/src/ui/screen/topNavigation.component.tsx
Labels: module:ui, needs review, next

#346 refactor(ui): apply radio mappings
  src/framework/ui/common/mapping.json
  src/framework/ui/radio/radio.component.tsx
  src/framework/ui/radio/radio.spec.tsx.snap
  src/playground/src/ui/screen/radio.component.tsx
Labels: module:ui, needs review, next

#343 refactor(ui): apply input mappings
  src/framework/ui/common/mapping.json
  src/framework/ui/input/input.component.tsx
  src/framework/ui/input/input.spec.tsx.snap
  src/playground/src/ui/screen/input.component.tsx
Labels: module:ui, needs review, next

#342 refactor(ui): apply checkbox mappings
  src/framework/ui/checkbox/checkbox.component.tsx
  src/framework/ui/checkbox/checkbox.spec.tsx.snap
  src/framework/ui/common/mapping.json
  src/framework/ui/drawable/checkmark/checkmark.component.tsx
  src/playground/src/ui/screen/checkbox.component.tsx
Labels: module:ui, needs review, next

#341 refactor(ui): apply bottom-navigation mappings
  src/framework/ui/bottomNavigation/bottomNavigation.component.tsx
  src/framework/ui/bottomNavigation/bottomNavigation.spec.tsx.snap
  src/framework/ui/bottomNavigation/bottomNavigationTab.component.tsx
  src/framework/ui/common/mapping.json
Labels: module:ui, needs review, next

#340 refactor(ui): apply avatar mappings
  src/framework/ui/avatar/avatar.spec.tsx.snap
  src/framework/ui/common/mapping.json
  src/playground/src/ui/screen/avatar.component.tsx
Labels: module:ui, needs review, next

#352 fix(ui): top-navigation align
  src/framework/ui/package-lock.json
  src/framework/ui/topNavigation/topNavigation.component.tsx
  src/framework/ui/topNavigation/topNavigation.spec.tsx.snap
  src/framework/ui/topNavigation/type.ts
Labels: module:ui, needs review, next

#361 feat(ui): input labels
  package-lock.json
  src/framework/ui/common/mapping.json
  src/framework/ui/input/input.component.tsx
  src/framework/ui/input/input.spec.tsx
  src/framework/ui/input/input.spec.tsx.snap
  src/playground/package-lock.json
  src/playground/src/ui/screen/input.component.tsx
Labels: module:ui, needs review, next

#364 fix(ui): input styles passing and applying fix
  src/framework/ui/common/props.ts
  src/framework/ui/input/input.component.tsx
  src/framework/ui/input/input.spec.tsx.snap
Labels: module:ui, needs review, next

#363 refactor(ui): tab-view enhancements
  src/framework/ui/tab/tab.component.tsx
  src/framework/ui/tab/tab.spec.tsx
  src/framework/ui/tab/tabBar.component.tsx
  src/framework/ui/tab/tabBarIndicator.component.tsx
  src/framework/ui/tab/tabView.component.tsx
  src/framework/ui/viewPager/viewPager.component.tsx
  src/framework/ui/viewPager/viewPager.spec.tsx
  src/playground/src/ui/screen/viewPager.component.tsx
Labels: module:ui, needs review, next

#367 fix(ui): container component interactions
  src/framework/ui/button/button.component.tsx
  src/framework/ui/button/button.spec.tsx.snap
  src/framework/ui/button/type.ts
  src/framework/ui/index.ts
  src/framework/ui/input/input.component.tsx
  src/framework/ui/input/input.spec.tsx.snap
  src/playground/src/ui/screen/button.component.tsx
Labels: module:ui, needs review, next

#366 refactor(mapping): update toggle mapping
  src/framework/ui/common/mapping.json
  src/framework/ui/toggle/toggle.component.tsx
  src/framework/ui/toggle/toggle.spec.tsx
  src/framework/ui/toggle/toggle.spec.tsx.snap
  src/playground/src/ui/screen/toggle.component.tsx
Labels: module:ui, needs review, next

#370 fix(ui): mapping find issues
  src/framework/theme/component/style/style.spec.tsx
  src/framework/theme/component/style/styleConsumer.component.tsx
  src/framework/ui/avatar/avatar.component.tsx
  src/framework/ui/bottomNavigation/bottomNavigation.component.tsx
  src/framework/ui/bottomNavigation/bottomNavigationTab.component.tsx
  src/framework/ui/button/button.component.tsx
  src/framework/ui/buttonGroup/buttonGroup.component.tsx
  src/framework/ui/checkbox/checkbox.component.tsx
  src/framework/ui/index.ts
  src/framework/ui/input/input.component.tsx
  src/framework/ui/layout/layout.component.tsx
  src/framework/ui/list/list.component.tsx
  src/framework/ui/list/listItem.component.tsx
  src/framework/ui/overflowMenu/overflowMenu.component.tsx
  src/framework/ui/overflowMenu/overflowMenuItem.component.tsx
  src/framework/ui/popover/popover.component.tsx
  src/framework/ui/radio/radio.component.tsx
  src/framework/ui/radioGroup/radioGroup.component.tsx
  src/framework/ui/tab/tab.component.tsx
  src/framework/ui/tab/tabBar.component.tsx
  src/framework/ui/text/text.component.tsx
  src/framework/ui/toggle/toggle.component.tsx
  src/framework/ui/tooltip/tooltip.component.tsx
  src/framework/ui/topNavigation/topNavigation.component.tsx
  src/framework/ui/topNavigation/topNavigationAction.component.tsx
Labels: module:ui, next

#371 fix(ui): popover margins offsets fix
  src/framework/ui/popover/popover.component.tsx
  src/framework/ui/popover/type.spec.ts
  src/framework/ui/popover/type.ts
Labels: module:ui, needs review, next

#369 fix(ui): export tab-view children props
  src/framework/ui/index.ts
  src/framework/ui/tab/tabView.component.tsx
Labels: module:ui, next

#372 fix(ui): update input mappings
  src/framework/ui/common/mapping.json
  src/framework/ui/input/input.spec.tsx.snap
Labels: module:ui, needs review, next

#373 fix(ui): update text mappings
  src/framework/ui/avatar/avatar.spec.tsx.snap
  src/framework/ui/bottomNavigation/bottomNavigation.spec.tsx.snap
  src/framework/ui/button/button.spec.tsx.snap
  src/framework/ui/checkbox/checkbox.spec.tsx.snap
  src/framework/ui/common/mapping.json
  src/framework/ui/common/theme.json
  src/framework/ui/input/input.spec.tsx.snap
  src/framework/ui/layout/layout.spec.tsx.snap
  src/framework/ui/list/list.spec.tsx.snap
  src/framework/ui/overflowMenu/overflowMenu.spec.tsx.snap
  src/framework/ui/radio/radio.spec.tsx.snap
  src/framework/ui/tab/tab.spec.tsx.snap
  src/framework/ui/text/text.component.tsx
  src/framework/ui/toggle/toggle.spec.tsx.snap
  src/framework/ui/topNavigation/topNavigation.spec.tsx.snap
Labels: module:ui, needs review, next

#374 fix(ui): view-pager swipe fix
  src/framework/ui/viewPager/viewPager.component.tsx
  src/playground/src/ui/screen/viewPager.component.tsx
Labels: module:ui, needs review, next

#376 refactor(ui): button-group layout refactor
  src/framework/ui/buttonGroup/buttonGroup.component.tsx
  src/framework/ui/buttonGroup/buttonGroup.spec.tsx
  src/framework/ui/buttonGroup/type.ts
  src/framework/ui/common/mapping.json
  src/playground/src/ui/screen/buttonGroup.component.tsx
Labels: module:ui, needs review, next

#375 fix(ui): button layout issues
  src/framework/ui/button/button.component.tsx
  src/framework/ui/button/button.spec.tsx.snap
  src/framework/ui/common/mapping.json
Labels: module:ui, needs review, next

#377 feat(ui): button "textStyle" property add
  src/framework/ui/button/button.component.tsx
  src/framework/ui/button/button.spec.tsx
  src/framework/ui/button/button.spec.tsx.snap
Labels: module:ui, needs review, next

#378 fix(ui): popover - scrollable container
  src/framework/ui/popover/popover.component.tsx
  src/framework/ui/popover/type.spec.ts
  src/framework/ui/popover/type.ts
Labels: module:ui, needs review, next

#380 fix(ui): popover - crash when no styles
  src/framework/ui/popover/type.ts
Labels: module:ui, needs review, next

#379 feat(ui): props for inline styling add
  src/framework/ui/bottomNavigation/bottomNavigation.component.tsx
  src/framework/ui/bottomNavigation/bottomNavigation.spec.tsx
  src/framework/ui/bottomNavigation/bottomNavigation.spec.tsx.snap
  src/framework/ui/bottomNavigation/bottomNavigationTab.component.tsx
  src/framework/ui/checkbox/checkbox.component.tsx
  src/framework/ui/checkbox/checkbox.spec.tsx
  src/framework/ui/checkbox/checkbox.spec.tsx.snap
  src/framework/ui/input/input.component.tsx
  src/framework/ui/input/input.spec.tsx
  src/framework/ui/input/input.spec.tsx.snap
  src/framework/ui/list/list.spec.tsx
  src/framework/ui/list/list.spec.tsx.snap
  src/framework/ui/list/listItem.component.tsx
  src/framework/ui/overflowMenu/overflowMenu.spec.tsx
  src/framework/ui/overflowMenu/overflowMenu.spec.tsx.snap
  src/framework/ui/overflowMenu/overflowMenuItem.component.tsx
  src/framework/ui/radio/radio.component.tsx
  src/framework/ui/radio/radio.spec.tsx
  src/framework/ui/radio/radio.spec.tsx.snap
  src/framework/ui/tab/tab.component.tsx
  src/framework/ui/tab/tab.spec.tsx
  src/framework/ui/tab/tab.spec.tsx.snap
  src/framework/ui/tab/tabBar.component.tsx
  src/framework/ui/tab/tabView.component.tsx
  src/framework/ui/tooltip/tooltip.component.tsx
  src/framework/ui/topNavigation/topNavigation.component.tsx
  src/framework/ui/topNavigation/topNavigation.spec.tsx
  src/framework/ui/topNavigation/topNavigation.spec.tsx.snap
  src/playground/src/ui/screen/bottomNavigation.component.tsx
  src/playground/src/ui/screen/overflowMenu.component.tsx
  src/playground/src/ui/screen/tooltip.component.tsx
Labels: module:ui, needs review, next

#381 Feat/button group statuses
  src/framework/ui/buttonGroup/buttonGroup.component.tsx
  src/framework/ui/common/mapping.json
  src/playground/src/ui/screen/buttonGroup.component.tsx
Labels: module:ui, needs review, next
