Repository akveo/react-native-ui-kitten, pull requests merged in 2019-07, with the labels that each got.

#492 feat(ui): input - icon press handler
  src/framework/ui/input/input.component.tsx
  src/framework/ui/input/input.spec.tsx
Labels: module:ui

#496 feat(docs): expand custom-mapping guide
  docs/src/articles/design-system/custom-mapping.md
Labels: module:docs

#490 feat(ui): react-native-web adopt
  docs/src/articles/guides/create-screen.md
  docs/src/articles/guides/install.md
  docs/src/articles/guides/using-web.md
  docs/src/structure.ts
  src/framework/theme/style/type.ts
  src/framework/ui/avatar/avatar.component.tsx
  src/framework/ui/bottomNavigation/bottomNavigation.component.tsx
  src/framework/ui/bottomNavigation/bottomNavigationTab.component.tsx
  src/framework/ui/button/button.component.tsx
  src/framework/ui/buttonGroup/buttonGroup.component.tsx
  src/framework/ui/checkbox/checkbox.component.tsx
  src/framework/ui/input/input.component.tsx
  src/framework/ui/layout/layout.component.tsx
  src/framework/ui/list/list.component.tsx
  src/framework/ui/list/listItem.component.tsx
  src/framework/ui/overflowMenu/overflowMenu.component.tsx
  src/framework/ui/overflowMenu/overflowMenuItem.component.tsx
  src/framework/ui/popover/popover.component.tsx
  src/framework/ui/popover/popoverView.component.tsx
  src/framework/ui/radio/radio.component.tsx
  src/framework/ui/radio/radio.spec.tsx.snap
  src/framework/ui/radioGroup/radioGroup.component.tsx
  src/framework/ui/support/components/arrow/arrow.component.tsx
  src/framework/ui/support/components/tabIndicator/tabIndicator.component.tsx
  src/framework/ui/support/typings/index.ts
  src/framework/ui/support/typings/type.ts
  src/framework/ui/tab/tab.component.tsx
  src/framework/ui/tab/tab.spec.tsx
  src/framework/ui/tab/tabBar.component.tsx
  src/framework/ui/tab/tabView.component.tsx
  src/framework/ui/text/text.component.tsx
  src/framework/ui/toggle/toggle.component.tsx
  src/framework/ui/tooltip/tooltip.component.tsx
  src/framework/ui/topNavigation/topNavigation.component.tsx
  src/framework/ui/topNavigation/topNavigationAction.component.tsx
  src/framework/ui/viewPager/viewPager.component.tsx
  src/framework/ui/viewPager/viewPager.spec.tsx
  src/playground/app.json
  src/playground/package-lock.json
  src/playground/package.json
  src/playground/src/app.component.tsx
  src/playground/src/assets/brand-logo.png
  src/playground/src/navigation/navigation.component.tsx
  src/playground/src/themes/index.ts
  src/playground/src/themes/themeContext.ts
  src/playground/src/ui/screen/home.component.tsx
  src/playground/src/ui/screen/index.ts
  src/playground/src/ui/screen/sample/sample.component.tsx
  src/playground/src/ui/screen/sample/sample.component.web.tsx
  src/playground/src/ui/screen/sample/sample.container.tsx
  src/playground/src/ui/screen/tabView/type.tsx
  src/playground/webpack.config.js
  tsconfig.dev.json
  tsconfig.prod.json
Labels: module:ui

#501 refactor(docs): docs prsr version update
  package-lock.json
  package.json
Labels: module:docs

#502 refactor(ui): modal component reimplement
  docs/package-lock.json
  docs/src/structure.ts
  src/framework/theme/modal/modalPanel.component.tsx
  src/framework/theme/modal/modalResolver.component.tsx
  src/framework/theme/modal/modalResolver.spec.tsx
  src/framework/theme/modal/modalResolver.spec.tsx.snap
  src/framework/ui/index.ts
  src/framework/ui/modal/modal.component.tsx
  src/framework/ui/modal/modal.spec.tsx
  src/playground/package-lock.json
  src/playground/src/navigation/navigation.component.tsx
  src/playground/src/ui/screen/common/showcaseSettings.component.tsx
  src/playground/src/ui/screen/home.component.tsx
  src/playground/src/ui/screen/index.ts
  src/playground/src/ui/screen/modal/modal.container.tsx
  src/playground/src/ui/screen/modal/modalShowcase.component.tsx
  src/playground/src/ui/screen/modal/type.ts
Labels: module:ui, needs review

#506 refactor(ui): modal-based components API refactor
  src/framework/theme/index.ts
  src/framework/theme/modal/modal.service.tsx
  src/framework/theme/modal/modalPanel.component.tsx
  src/framework/theme/modal/modalPanel.spec.tsx
  src/framework/theme/modal/modalResolver.component.tsx
  src/framework/theme/modal/modalResolver.spec.tsx
  src/framework/theme/modal/modalResolver.spec.tsx.snap
  src/framework/ui/modal/modal.component.tsx
  src/framework/ui/overflowMenu/overflowMenu.component.tsx
  src/framework/ui/overflowMenu/overflowMenu.spec.tsx
  src/framework/ui/overflowMenu/overflowMenu.spec.tsx.snap
  src/framework/ui/popover/popover.component.tsx
  src/framework/ui/support/typings/index.ts
  src/framework/ui/support/typings/type.ts
  src/framework/ui/tab/tab.spec.tsx
  src/framework/ui/tooltip/tooltip.component.tsx
  src/playground/src/ui/screen/common/showcaseSettings.component.tsx
  src/playground/src/ui/screen/modal/modalShowcase.component.tsx
  src/playground/src/ui/screen/modal/type.ts
  src/playground/src/ui/screen/overflowMenu/overflowMenuShowcase.component.tsx
  src/playground/src/ui/screen/popover/popoverShowcase.component.tsx
  src/playground/src/ui/screen/tooltip/tooltipShowcase.component.tsx
Labels: enhancement, module:ui

#507 docs(guides): fix create-screen import typo
  docs/src/articles/guides/create-screen.md
Labels: module:docs

#514 fix(docs): landing style fix
  docs/src/landing/css/reactive-kitten.webflow.css
Labels: module:docs

#518 feat(docs): overview-examples handling add
  docs/src/app/@theme/styles/styles.scss
  docs/src/app/blocks/blocks.module.ts
  docs/src/app/blocks/components/code-block/code-block.component.scss
  docs/src/app/blocks/components/index.ts
  docs/src/app/blocks/components/overview-block/overview-block.component.ts
  docs/src/app/blocks/components/overview-example-block/overview-example-block.component.ts
  package-lock.json
  package.json
  src/framework/ui/button/button.component.tsx
  src/framework/ui/modal/modal.component.tsx
Labels: enhancement, module:docs

#527 fix(ui): modal docs fix
  src/framework/ui/modal/modal.component.tsx
Labels: module:docs

#533 feat(ui): popover - autoplacement
  src/framework/ui/popover/placement.service.ts
  src/framework/ui/popover/popover.component.tsx
  src/framework/ui/popover/type.spec.ts
  src/framework/ui/popover/type.ts
Labels: module:ui

#540 refactor(ui): bottom-navigation documentation update
  src/framework/ui/bottomNavigation/bottomNavigation.component.tsx
Labels: enhancement, module:docs

#542 feat(ui/theme): "modal-team" missing update functionality add
  src/framework/theme/modal/modal.service.tsx
  src/framework/theme/modal/modalPanel.component.tsx
  src/framework/ui/modal/modal.component.tsx
  src/framework/ui/modal/modal.spec.tsx
  src/framework/ui/popover/popover.component.tsx
  src/framework/ui/support/typings/type.ts
  src/playground/package-lock.json
Labels: module:ui

#549 fix(ui): view-pager - external state control
  src/framework/ui/viewPager/viewPager.component.tsx
Labels: module:ui
