Repository akveo/react-native-ui-kitten, pull requests merged in 2019-08, with the labels that each got.

#563 build(common): update expo to sdk 34
  package-lock.json
  package.json
  src/playground/app.json
  src/playground/package-lock.json
  src/playground/package.json
Labels: module:build

#561 fix(ui): add rtl fixes and demo
  src/framework/ui/input/input.component.tsx
  src/framework/ui/list/listItem.component.tsx
  src/framework/ui/popover/popoverView.component.tsx
  src/framework/ui/popover/type.ts
  src/framework/ui/support/components/checkmark/checkmark.component.tsx
  src/framework/ui/support/components/tabIndicator/tabIndicator.component.tsx
  src/framework/ui/support/services/i18n/i18nLayout.service.ts
  src/framework/ui/support/services/i18n/i18nLayout.spec.ts
  src/framework/ui/support/services/i18n/i18nLayoutFlexMap.ts
  src/framework/ui/support/services/i18n/type.ts
  src/framework/ui/support/services/index.ts
  src/framework/ui/toggle/toggle.component.tsx
  src/framework/ui/viewPager/viewPager.component.tsx
  src/playground/src/ui/screen/common/showcaseItem.component.tsx
  src/playground/src/ui/screen/common/showcaseSection.component.tsx
  src/playground/src/ui/screen/common/showcaseSettings.component.tsx
  src/playground/src/ui/screen/home.component.tsx
Labels: module:ui, needs review

#556 feat(template): add ui-kitten template projects
  README.md
  docs/src/articles/getting-started/where-to-start.md
  docs/src/articles/guides/install-existing.md
  docs/src/articles/guides/install-new.md
  docs/src/articles/guides/install.md
  docs/src/structure.ts
  package-lock.json
  package.json
  src/playground/package-lock.json
  src/templates/template-ui-kitten-typescript/App.tsx
  src/templates/template-ui-kitten-typescript/_tsconfig.json
  src/templates/template-ui-kitten-typescript/dependencies.json
  src/templates/template-ui-kitten-typescript/devDependencies.json
  src/templates/template-ui-kitten-typescript/install.js
  src/templates/template-ui-kitten-typescript/jest.config.js
  src/templates/template-ui-kitten-typescript/package.json
  src/templates/template-ui-kitten/App.js
  src/templates/template-ui-kitten/dependencies.json
  src/templates/template-ui-kitten/package.json
  tsconfig.dev.json
  tsconfig.json
Labels: module:cli-template

#526 feat(eva-icons): add eva-icons module
  babel.config.js
  config/dev.env.js
  config/prod.env.js
  docs/src/articles/guides/setup-icons-module.md
  docs/src/articles/guides/setup-vector-icons.md
  docs/src/assets/images/articles/guides/3rd-party-icons-feather.png
  docs/src/assets/images/articles/guides/3rd-party-icons-material.png
  docs/src/assets/images/articles/guides/3rd-party-icons-sample.png
  docs/src/assets/images/articles/guides/sample-icon-button.png
  docs/src/assets/images/components/icon.svg
  docs/src/assets/images/overview/icon.png
  docs/src/structure.ts
  package-lock.json
  package.json
  scripts/build/compile-ts.sh
  src/eva-icons/createIconsMap.ts
  src/eva-icons/evaIcon.component.tsx
  src/eva-icons/index.ts
  src/eva-icons/package.json
  src/framework/ui/animation/animation.ts
  src/framework/ui/animation/index.ts
  src/framework/ui/animation/pulseAnimation.ts
  src/framework/ui/animation/shakeAnimation.ts
  src/framework/ui/animation/zoomAnimation.ts
  src/framework/ui/icon/icon.component.tsx
  src/framework/ui/icon/icon.spec.tsx
  src/framework/ui/icon/iconAnimation.ts
  src/framework/ui/icon/iconRegistry.component.tsx
  src/framework/ui/icon/service/iconRegistry.service.ts
  src/framework/ui/icon/service/iconRegistry.spec.tsx
  src/framework/ui/icon/service/type.ts
  src/framework/ui/index.ts
  src/playground/babel.config.js
  src/playground/metro.config.js
  src/playground/package-lock.json
  src/playground/src/app.component.tsx
  src/playground/src/icons/ant.tsx
  src/playground/src/icons/feather.tsx
  src/playground/src/icons/fontAwesome.tsx
  src/playground/src/icons/index.ts
  src/playground/src/icons/material.tsx
  src/playground/src/icons/materialCommunity.tsx
  src/playground/src/navigation/navigation.component.tsx
  src/playground/src/ui/screen/button/type.tsx
  src/playground/src/ui/screen/home.component.tsx
  src/playground/src/ui/screen/icon/icon.container.tsx
  src/playground/src/ui/screen/icon/iconShowcase.component.tsx
  src/playground/src/ui/screen/icon/type.ts
  src/playground/src/ui/screen/index.ts
  src/playground/src/ui/screen/input/type.tsx
  src/playground/src/ui/screen/list/listItemShowcase.component.tsx
  src/playground/src/ui/screen/overflowMenu/type.tsx
  src/playground/src/ui/screen/sample/sample.component.tsx
  src/playground/src/ui/screen/sample/sample.component.web.tsx
  src/playground/src/ui/screen/topNavigation/type.tsx
  tsconfig.json
Labels: module:icons, module:ui

#545 feat(ui): spinner component
  docs/src/assets/images/components/spinner.svg
  docs/src/assets/images/overview/spinner.png
  docs/src/structure.ts
  package-lock.json
  src/framework/ui/index.ts
  src/framework/ui/spinner/animation.ts
  src/framework/ui/spinner/spinner.component.tsx
  src/playground/package-lock.json
  src/playground/src/navigation/navigation.component.tsx
  src/playground/src/ui/screen/home.component.tsx
  src/playground/src/ui/screen/index.ts
  src/playground/src/ui/screen/spinner/spinner.container.tsx
  src/playground/src/ui/screen/spinner/spinnerShowcase.component.tsx
  src/playground/src/ui/screen/spinner/type.ts
Labels: module:ui

#544 feat(ui): dropdown component add
  docs/src/structure.ts
  src/framework/theme/style/type.ts
  src/framework/ui/dropdown/dropdown.component.tsx
  src/framework/ui/dropdown/dropdown.spec.tsx
  src/framework/ui/dropdown/dropdownGroup.component.tsx
  src/framework/ui/dropdown/dropdownMenu.component.tsx
  src/framework/ui/dropdown/droppdownItem.component.tsx
  src/framework/ui/dropdown/selection.strategy.ts
  src/framework/ui/index.ts
  src/framework/ui/support/components/chevron/chevron.component.tsx
  src/framework/ui/support/components/index.ts
  src/framework/ui/support/services/index.ts
  src/framework/ui/support/services/props.service.ts
  src/framework/ui/support/tests/mapping.json
  src/framework/ui/support/typings/index.ts
  src/framework/ui/support/typings/type.ts
  src/playground/src/navigation/navigation.component.tsx
  src/playground/src/ui/screen/dropdown/dropdown.container.tsx
  src/playground/src/ui/screen/dropdown/dropdownShowcase.component.tsx
  src/playground/src/ui/screen/dropdown/type.tsx
  src/playground/src/ui/screen/home.component.tsx
  src/playground/src/ui/screen/index.ts
Labels: module:ui, needs review

#557 docs(ui): overview-examples add
  src/framework/theme/application/applicationProvider.component.tsx
  src/framework/theme/modal/modal.service.tsx
  src/framework/theme/style/style.service.ts
  src/framework/theme/style/styleConsumer.component.tsx
  src/framework/theme/style/styleConsumer.service.ts
  src/framework/theme/theme/theme.service.ts
  src/framework/theme/theme/themeConsumer.component.tsx
  src/framework/theme/theme/themeContext.ts
  src/framework/ui/avatar/avatar.component.tsx
  src/framework/ui/bottomNavigation/bottomNavigation.component.tsx
  src/framework/ui/bottomNavigation/bottomNavigationTab.component.tsx
  src/framework/ui/button/button.component.tsx
  src/framework/ui/buttonGroup/buttonGroup.component.tsx
  src/framework/ui/checkbox/checkbox.component.tsx
  src/framework/ui/input/input.component.tsx
  src/framework/ui/layout/layout.component.tsx
  src/framework/ui/list/list.component.tsx
  src/framework/ui/list/listItem.component.tsx
  src/framework/ui/modal/modal.component.tsx
  src/framework/ui/overflowMenu/overflowMenu.component.tsx
  src/framework/ui/overflowMenu/overflowMenuItem.component.tsx
  src/framework/ui/popover/measure.component.tsx
  src/framework/ui/popover/placement.service.ts
  src/framework/ui/popover/popover.component.tsx
  src/framework/ui/popover/popoverView.component.tsx
  src/framework/ui/popover/type.ts
  src/framework/ui/radio/radio.component.tsx
  src/framework/ui/radioGroup/radioGroup.component.tsx
  src/framework/ui/tab/tab.component.tsx
  src/framework/ui/tab/tabBar.component.tsx
  src/framework/ui/tab/tabView.component.tsx
  src/framework/ui/text/text.component.tsx
  src/framework/ui/toggle/toggle.component.tsx
  src/framework/ui/tooltip/tooltip.component.tsx
  src/framework/ui/topNavigation/topNavigation.component.tsx
  src/framework/ui/topNavigation/topNavigationAction.component.tsx
  src/framework/ui/viewPager/viewPager.component.tsx
Labels: module:docs

#576 Refactor/dropdown
  src/framework/ui/index.ts
  src/framework/ui/select/select.component.tsx
  src/framework/ui/select/select.spec.tsx
  src/framework/ui/select/selectGroupOption.component.tsx
  src/framework/ui/select/selectOption.component.tsx
  src/framework/ui/select/selectOptionsList.component.tsx
  src/framework/ui/select/selection.strategy.ts
  src/framework/ui/support/tests/mapping.json
  src/playground/src/navigation/navigation.component.tsx
  src/playground/src/ui/screen/dropdown/dropdown.container.tsx
  src/playground/src/ui/screen/dropdown/dropdownShowcase.component.tsx
  src/playground/src/ui/screen/home.component.tsx
  src/playground/src/ui/screen/index.ts
  src/playground/src/ui/screen/select/select.container.tsx
  src/playground/src/ui/screen/select/selectShowcase.component.tsx
  src/playground/src/ui/screen/select/type.tsx
Labels: module:ui, needs review

#572 feat(ui): menu component
  docs/src/landing/js/webflow.js
  docs/src/structure.ts
  scripts/build/compile-ts.sh
  src/framework/ui/divider/divider.component.tsx
  src/framework/ui/index.ts
  src/framework/ui/list/listItem.component.tsx
  src/framework/ui/menu/menu.component.tsx
  src/framework/ui/menu/menu.service.ts
  src/framework/ui/menu/menu.spec.tsx
  src/framework/ui/menu/menuItem.component.tsx
  src/framework/ui/menu/subMenu.component.tsx
  src/framework/ui/select/select.component.tsx
  src/framework/ui/support/components/chevron/chevron.component.tsx
  src/framework/ui/support/tests/mapping.json
  src/playground/src/navigation/navigation.component.tsx
  src/playground/src/ui/screen/home.component.tsx
  src/playground/src/ui/screen/index.ts
  src/playground/src/ui/screen/menu/menu.container.tsx
  src/playground/src/ui/screen/menu/menuShowcase.component.tsx
  src/playground/src/ui/screen/menu/type.tsx
Labels: module:ui, needs review

#578 fix(view pager): slides could go out of boundary
  src/framework/ui/viewPager/viewPager.component.tsx
Labels: module:ui

#579 refactor(ui): select styles names refactor
  src/framework/ui/select/select.component.tsx
  src/framework/ui/support/tests/mapping.json
Labels: module:ui

#580 refactor(ui): overflow-menu re-implement
  docs/src/structure.ts
  src/framework/ui/index.ts
  src/framework/ui/overflowMenu/overflowMenu.component.tsx
  src/framework/ui/overflowMenu/overflowMenu.spec.tsx
  src/framework/ui/overflowMenu/overflowMenu.spec.tsx.snap
  src/framework/ui/overflowMenu/overflowMenuItem.component.tsx
  src/framework/ui/popover/measure.component.tsx
  src/framework/ui/support/tests/mapping.json
  src/framework/ui/support/typings/index.ts
  src/playground/src/ui/screen/common/showcaseSettings.component.tsx
  src/playground/src/ui/screen/overflowMenu/overflowMenuShowcase.component.tsx
  src/playground/src/ui/screen/overflowMenu/type.tsx
Labels: module:ui, needs review

#575 refactor(ui): spinner playground and documentation refactor
  src/framework/ui/spinner/spinner.component.tsx
  src/playground/src/ui/screen/spinner/type.ts
Labels: module:playground

#543 feat(ui): drawer component
  README.md
  docs/src/articles/getting-started/where-to-start.md
  docs/src/articles/guides/install-existing.md
  docs/src/articles/guides/install-new.md
  docs/src/articles/guides/install.md
  docs/src/assets/images/components/drawer.svg
  docs/src/assets/images/overview/drawer.png
  docs/src/structure.ts
  src/framework/ui/drawer/drawer.component.tsx
  src/framework/ui/drawer/drawer.spec.tsx
  src/framework/ui/drawer/drawerFence.component.tsx
  src/framework/ui/index.ts
  src/framework/ui/list/list.component.tsx
  src/framework/ui/support/tests/mapping.json
  src/playground/package-lock.json
  src/playground/src/navigation/drawerNavigation.component.tsx
  src/playground/src/navigation/navigation.component.tsx
  src/playground/src/ui/screen/drawer/drawer.container.tsx
  src/playground/src/ui/screen/drawer/drawerShowcase.component.tsx
  src/playground/src/ui/screen/drawer/type.tsx
  src/playground/src/ui/screen/home.component.tsx
  src/playground/src/ui/screen/index.ts
  src/templates/template-ui-kitten-typescript/App.tsx
  src/templates/template-ui-kitten-typescript/_tsconfig.json
  src/templates/template-ui-kitten-typescript/dependencies.json
  src/templates/template-ui-kitten-typescript/devDependencies.json
  src/templates/template-ui-kitten-typescript/install.js
  src/templates/template-ui-kitten-typescript/jest.config.js
  src/templates/template-ui-kitten-typescript/package.json
  src/templates/template-ui-kitten/App.js
  src/templates/template-ui-kitten/dependencies.json
  src/templates/template-ui-kitten/package.json
  tsconfig.dev.json
Labels: module:ui

#585 fix(ui): sub-menu components items onPress handling fix
  src/framework/ui/menu/subMenu.component.tsx
  src/playground/metro.config.js
Labels: module:ui

#590 fix(release): publish scripts and versions fix
  package-lock.json
  package.json
  scripts/publish/publish-framework.sh
  scripts/publish/publish-modules.sh
  src/framework/package.json
  src/playground/package-lock.json
  src/playground/package.json
  src/templates/template-ui-kitten-typescript/dependencies.json
  src/templates/template-ui-kitten/dependencies.json
Labels: needs review

#591 release: v4.2.0-beta.2
  CHANGELOG.md
  package-lock.json
  package.json
  src/eva-icons/package.json
  src/framework/package.json
  src/templates/template-ui-kitten-typescript/dependencies.json
  src/templates/template-ui-kitten-typescript/package.json
  src/templates/template-ui-kitten/dependencies.json
  src/templates/template-ui-kitten/package.json
Labels: needs review

#592 refactor(docs): drawer/icon/select/spinner documentation refactor
  src/framework/ui/checkbox/checkbox.component.tsx
  src/framework/ui/drawer/drawer.component.tsx
  src/framework/ui/icon/icon.component.tsx
  src/framework/ui/layout/layout.component.tsx
  src/framework/ui/select/select.component.tsx
  src/framework/ui/spinner/spinner.component.tsx
Labels: module:docs, needs review
