Repository akveo/react-native-ui-kitten, pull requests merged in 2019-05, with the labels that each got.

#383 fix(ui): list-item style
  src/framework/ui/list/listItem.component.tsx
Labels: next

#387 docs(theme): add theme components documentation
  src/framework/theme/application/applicationProvider.component.tsx
  src/framework/theme/style/styleConsumer.component.tsx
  src/framework/theme/theme/themeConsumer.component.tsx
Labels: module:theme, needs review, next

#388 docs(guides): add getting-started and theme-system guides
  docs/src/app/@theme/services/structure.service.ts
  docs/src/articles/index.md
  docs/src/guides/index.md
  docs/src/guides/install-into-existing.md
  docs/src/guides/start.md
  docs/src/guides/theme-customize-component.md
  docs/src/guides/theme-system.md
  docs/src/guides/theme-using-mapping.md
  docs/src/guides/theme-using-variables.md
  docs/src/structure.ts
  src/playground/src/app.component.tsx
Labels: module:docs, needs review, next

#389 refactor(docs): hoc docs and doc-app refactor
  docs/src/app/@theme/services/tabbed.service.ts
  docs/src/app/blocks/blocks.module.ts
  docs/src/app/blocks/components/api-block/api-block.component.ts
  docs/src/app/blocks/components/hoc-params-block/hoc-params-block.component.ts
  docs/src/app/blocks/components/index.ts
  docs/src/app/blocks/components/overview-block/overview-block.component.ts
  docs/src/guides/theme-switching.md
  docs/src/structure.ts
  src/framework/theme/application/applicationProvider.component.tsx
  src/framework/theme/style/styleConsumer.component.tsx
  src/framework/theme/theme/themeConsumer.component.tsx
  src/framework/ui/avatar/avatar.component.tsx
  src/framework/ui/bottomNavigation/bottomNavigation.component.tsx
  src/framework/ui/bottomNavigation/bottomNavigationTab.component.tsx
  src/framework/ui/button/button.component.tsx
  src/framework/ui/buttonGroup/buttonGroup.component.tsx
  src/framework/ui/checkbox/checkbox.component.tsx
  src/framework/ui/input/input.component.tsx
  src/framework/ui/layout/layout.component.tsx
  src/framework/ui/list/list.component.tsx
  src/framework/ui/list/listItem.component.tsx
  src/framework/ui/modal/modal.component.tsx
  src/framework/ui/overflowMenu/overflowMenu.component.tsx
  src/framework/ui/popover/popover.component.tsx
  src/framework/ui/radio/radio.component.tsx
  src/framework/ui/radioGroup/radioGroup.component.tsx
  src/framework/ui/tab/tab.component.tsx
  src/framework/ui/tab/tabBar.component.tsx
  src/framework/ui/tab/tabView.component.tsx
  src/framework/ui/text/text.component.tsx
  src/framework/ui/toggle/toggle.component.tsx
  src/framework/ui/tooltip/tooltip.component.tsx
  src/framework/ui/topNavigation/topNavigation.component.tsx
  src/framework/ui/viewPager/viewPager.component.tsx
  src/playground/src/ui/screen/listItem.showcase.component.tsx
  src/playground/src/ui/screen/tabView.component.tsx
  src/playground/src/ui/screen/viewPager.component.tsx
Labels: module:docs, needs review, next

#390 fix(ui): common issues
  src/framework/ui/avatar/avatar.component.tsx
  src/framework/ui/topNavigation/topNavigation.component.tsx
  src/framework/ui/topNavigation/topNavigationAction.component.tsx
Labels: module:ui, needs review, next

#391 package(common): update typing packages versions
  babel.config.js
  package-lock.json
  package.json
  src/framework/theme/modal/modalPanel.spec.tsx.snap
  src/framework/theme/package.json
  src/framework/theme/style/styleConsumer.component.tsx
  src/framework/theme/theme/themeConsumer.component.tsx
  src/framework/ui/modal/modal.spec.tsx.snap
  src/framework/ui/overflowMenu/overflowMenu.spec.tsx.snap
  src/framework/ui/package-lock.json
  src/framework/ui/package.json
  src/framework/ui/radio/radio.spec.tsx.snap
  src/playground/babel.config.js
  src/playground/package-lock.json
  src/playground/package.json
Labels: module:build, next

#392 fix(ui): top-navigation-bar fix
  src/framework/ui/support/tests/mapping.json
  src/framework/ui/topNavigation/topNavigation.component.tsx
  src/framework/ui/topNavigation/topNavigationAction.component.tsx
  src/framework/ui/topNavigation/type.ts
  src/playground/app.json
  src/playground/src/ui/screen/topNavigation.component.tsx
Labels: module:ui, needs review, next

#393 build(common): setup playground to watch eva changes
  babel.config.js
  src/framework/theme/support/tests/mapping.json
  src/framework/ui/support/tests/mapping.json
  src/playground/babel.config.js
  src/playground/metro.config.js
  src/playground/tsconfig.json
Labels: module:build, next

#394 build(common): setup env configurations
  .gitignore
  config/dev.env.js
  config/prod.env.js
  package.json
  scripts/environment/set-env.sh
  src/playground/babel.config.js
  src/playground/metro.config.js
  src/playground/package.json
  src/playground/tsconfig.json
Labels: next

#395 refactor(test): button test config refactored according to the missing properties "eva-refactoring"
  src/framework/ui/support/tests/mapping.json
  src/playground/package-lock.json
Labels: needs review, next

#397 fix(ui): adopt to eva
  .travis.yml
  config/dev.env.js
  config/prod.env.js
  package.json
  src/framework/ui/buttonGroup/buttonGroup.component.tsx
  src/framework/ui/checkbox/checkbox.component.tsx
  src/framework/ui/input/input.component.tsx
  src/framework/ui/list/listItem.component.tsx
  src/framework/ui/overflowMenu/overflowMenu.component.tsx
  src/framework/ui/radio/radio.component.tsx
  src/framework/ui/radio/radio.spec.tsx.snap
  src/framework/ui/support/tests/mapping.json
  src/framework/ui/support/tests/theme.json
  src/framework/ui/toggle/toggle.component.tsx
  src/framework/ui/tooltip/tooltip.component.tsx
  src/playground/babel.config.js
  src/playground/metro.config.js
  src/playground/package-lock.json
Labels: module:ui, needs review, next

#398 feat(theme): referencing values
  src/framework/theme/application/application.spec.tsx.snap
  src/framework/theme/support/tests/theme.json
  src/framework/theme/theme/theme.service.ts
  src/framework/theme/theme/theme.spec.tsx
Labels: module:theme, needs review, next

#399 fix(theme): theme change fix
  package-lock.json
  src/framework/theme/application/application.spec.tsx
  src/framework/theme/application/applicationProvider.component.tsx
  src/framework/theme/modal/modalPanel.spec.tsx.snap
  src/framework/theme/style/style.spec.tsx.snap
  src/framework/theme/support/tests/themeInverse.json
  src/framework/ui/modal/modal.spec.tsx.snap
  src/framework/ui/overflowMenu/overflowMenu.spec.tsx.snap
  src/framework/ui/radio/radio.spec.tsx.snap
  src/playground/package-lock.json
Labels: module:theme, needs review, next

#400 refactor(playground): screen refactor
  src/playground/src/app.component.tsx
  src/playground/src/navigation/index.ts
  src/playground/src/navigation/navigation.component.tsx
  src/playground/src/ui/screen/avatar.component.tsx
  src/playground/src/ui/screen/avatar/avatar.container.tsx
  src/playground/src/ui/screen/avatar/type.ts
  src/playground/src/ui/screen/bottomNavigation.component.tsx
  src/playground/src/ui/screen/button/button.container.tsx
  src/playground/src/ui/screen/button/type.tsx
  src/playground/src/ui/screen/buttonGroup.component.tsx
  src/playground/src/ui/screen/checkbox/checkbox.container.tsx
  src/playground/src/ui/screen/checkbox/type.ts
  src/playground/src/ui/screen/common/showcase.component.tsx
  src/playground/src/ui/screen/common/showcaseItem.component.tsx
  src/playground/src/ui/screen/common/showcaseSection.component.tsx
  src/playground/src/ui/screen/common/type.ts
  src/playground/src/ui/screen/home.component.tsx
  src/playground/src/ui/screen/index.ts
  src/playground/src/ui/screen/input/input.container.tsx
  src/playground/src/ui/screen/input/type.tsx
  src/playground/src/ui/screen/layout.component.tsx
  src/playground/src/ui/screen/list.component.tsx
  src/playground/src/ui/screen/overflowMenu.component.tsx
  src/playground/src/ui/screen/popover.component.tsx
  src/playground/src/ui/screen/radio/radio.container.tsx
  src/playground/src/ui/screen/radio/type.ts
  src/playground/src/ui/screen/radioGroup.component.tsx
  src/playground/src/ui/screen/tabBar.component.tsx
  src/playground/src/ui/screen/tabView.component.tsx
  src/playground/src/ui/screen/text.component.tsx
  src/playground/src/ui/screen/toggle/toggle.container.tsx
  src/playground/src/ui/screen/toggle/type.ts
  src/playground/src/ui/screen/tooltip.component.tsx
  src/playground/src/ui/screen/topNavigation.component.tsx
  src/playground/src/ui/screen/viewPager.component.tsx
  src/playground/src/ui/themeConsumer.tsx
  src/playground/src/ui/themeContext.ts
Labels: module:playground, needs review, next

#401 fix(framework): eva-adopt
  config/prod.env.js
  docs/src/guides/install-into-existing.md
  docs/src/guides/theme-customize-component.md
  docs/src/guides/theme-switching.md
  docs/src/guides/theme-system.md
  docs/src/guides/theme-using-mapping.md
  package-lock.json
  src/framework/theme/application/application.spec.tsx.snap
  src/framework/theme/application/applicationProvider.component.tsx
  src/framework/theme/style/style.service.ts
  src/framework/theme/support/tests/theme.json
  src/framework/theme/theme/theme.service.ts
  src/framework/theme/theme/theme.spec.tsx
  src/framework/theme/theme/themeConsumer.component.tsx
  src/framework/ui/input/input.component.tsx
  src/framework/ui/radio/radio.spec.tsx.snap
  src/framework/ui/support/tests/mapping.json
  src/framework/ui/support/tests/theme.json
  src/framework/ui/tab/tabView.component.tsx
  src/playground/babel.config.js
  src/playground/package-lock.json
  src/playground/package.json
  src/playground/src/app.component.tsx
Labels: module:theme, module:ui, needs review, next

#402 fix(ui): top-navigation style apply
  src/framework/ui/topNavigation/topNavigation.component.tsx
Labels: module:ui, next

#403 refactor(ui): radio/button hit-slopes add
  src/framework/ui/checkbox/checkbox.component.tsx
  src/framework/ui/radio/radio.component.tsx
  src/framework/ui/radio/radio.spec.tsx.snap
  src/framework/ui/support/tests/mapping.json
Labels: module:ui, needs review, next

#404 fix(ui): popover position
  src/framework/ui/popover/popover.component.tsx
Labels: next

#406 feat(ui): popover indicator style
  src/framework/ui/overflowMenu/overflowMenu.component.tsx
  src/framework/ui/popover/popover.component.tsx
  src/framework/ui/popover/popoverView.component.tsx
  src/framework/ui/tooltip/tooltip.component.tsx
Labels: module:ui, needs review, next

#407 refactor(ui): radio/checkbox size variant remove
  config/dev.env.js
  src/framework/ui/checkbox/checkbox.component.tsx
  src/framework/ui/radio/radio.component.tsx
  src/framework/ui/radio/radio.spec.tsx.snap
  src/framework/ui/radioGroup/radioGroup.component.tsx
  src/framework/ui/support/tests/mapping.json
  src/playground/package-lock.json
  src/playground/src/navigation/index.ts
  src/playground/src/navigation/navigation.component.tsx
  src/playground/src/ui/screen/checkbox.component.tsx
  src/playground/src/ui/screen/checkbox/type.ts
  src/playground/src/ui/screen/home.component.tsx
  src/playground/src/ui/screen/radio.component.tsx
  src/playground/src/ui/screen/radio/type.ts
  src/playground/src/ui/screen/radioGroup.component.tsx
Labels: module:ui, needs review, next
