Repository akveo/react-native-ui-kitten, pull requests merged in 2019-03, with the labels that each got.

#291 feat(ui): button-group component. Closes #290
  src/framework/ui/button/button.component.tsx
  src/framework/ui/button/button.spec.tsx.snap
  src/framework/ui/buttonGroup/buttonGroup.component.tsx
  src/framework/ui/buttonGroup/buttonGroup.spec.config.ts
  src/framework/ui/buttonGroup/buttonGroup.spec.tsx
  src/framework/ui/buttonGroup/type.ts
  src/framework/ui/index.ts
  src/playground/src/ui/screen/buttonGroup.component.tsx
  src/playground/src/ui/screen/index.ts
Labels: module:ui, needs review, next

#296 refactor(theme): adopt to eva mapping structure. Closes #266
  src/framework/theme/component/application/application.spec.config.ts
  src/framework/theme/component/application/application.spec.tsx
  src/framework/theme/component/application/applicationProvider.component.tsx
  src/framework/theme/component/mapping/mapping.spec.tsx
  src/framework/theme/component/mapping/mappingContext.ts
  src/framework/theme/component/mapping/mappingProvider.component.tsx
  src/framework/theme/component/style/style.spec.config.ts
  src/framework/theme/component/style/style.spec.tsx
  src/framework/theme/component/style/styleConsumer.component.tsx
  src/framework/theme/service/style/style.service.ts
  src/framework/theme/service/style/style.spec.config.ts
  src/framework/theme/service/style/styleConsumer.service.ts
  src/framework/ui/button/button.component.tsx
  src/framework/ui/button/button.spec.config.ts
  src/framework/ui/button/button.spec.tsx.snap
  src/framework/ui/buttonGroup/buttonGroup.spec.config.ts
  src/framework/ui/checkbox/checkbox.component.tsx
  src/framework/ui/checkbox/checkbox.spec.config.ts
  src/framework/ui/layout/layout.spec.config.ts
  src/framework/ui/modal/modal.spec.config.ts
  src/framework/ui/modal/modal.spec.tsx.snap
  src/framework/ui/popover/type.spec.ts
  src/framework/ui/radio/radio.component.tsx
  src/framework/ui/radio/radio.spec.config.ts
  src/framework/ui/radio/radio.spec.tsx.snap
  src/framework/ui/radioGroup/radioGroup.spec.config.ts
  src/framework/ui/tab/tab.spec.contig.ts
  src/framework/ui/tab/tab.spec.tsx.snap
  src/framework/ui/tab/tabBar.component.tsx
  src/framework/ui/tabNavigator/bottomNavigatorTab.component.tsx
  src/framework/ui/tabNavigator/bottomNavigatorTab.spec.config.ts
  src/framework/ui/tabNavigator/bottomTabNavigator.component.tsx
  src/framework/ui/tabNavigator/bottomTabNavigator.spec.config.ts
  src/framework/ui/tabNavigator/bottomTabNavigator.spec.tsx.snap
  src/framework/ui/toggle/toggle.component.tsx
  src/framework/ui/toggle/toggle.spec.config.ts
  src/framework/ui/toggle/toggle.spec.tsx.snap
  src/framework/ui/topNavigationBar/topNavigationBar.component.tsx
  src/framework/ui/topNavigationBar/topNavigationBar.spec.config.ts
  src/framework/ui/topNavigationBar/topNavigationBar.spec.tsx.snap
  src/playground/src/app.component.tsx
  src/playground/src/ui/screen/button.component.tsx
  src/playground/src/ui/screen/checkbox.component.tsx
  src/playground/src/ui/screen/radio.component.tsx
  src/playground/src/ui/screen/radioGroup.component.tsx
  src/playground/src/ui/screen/tabNavigator.component.tsx
  src/playground/src/ui/screen/toggle.component.tsx
  src/playground/src/ui/screen/topNavigationBar.component.tsx
Labels: module:theme, needs review, next

#292 refactor(ui): icons integration
  package-lock.json
  src/framework/ui/button/button.component.tsx
  src/framework/ui/button/button.spec.tsx
  src/framework/ui/button/button.spec.tsx.snap
  src/framework/ui/buttonGroup/buttonGroup.component.tsx
  src/framework/ui/checkbox/checkbox.component.tsx
  src/framework/ui/popover/measure.component.tsx
  src/framework/ui/popover/popover.component.tsx
  src/framework/ui/popover/popoverView.component.tsx
  src/framework/ui/radio/radio.component.tsx
  src/framework/ui/radioGroup/radioGroup.component.tsx
  src/framework/ui/tab/tab.component.tsx
  src/framework/ui/tab/tab.spec.contig.ts
  src/framework/ui/tab/tab.spec.tsx
  src/framework/ui/tab/tab.spec.tsx.snap
  src/framework/ui/tab/tabBar.component.tsx
  src/framework/ui/tab/tabView.component.tsx
  src/framework/ui/tabNavigator/bottomNavigatorTab.component.tsx
  src/framework/ui/tabNavigator/bottomNavigatorTab.spec.config.ts
  src/framework/ui/tabNavigator/bottomNavigatorTab.spec.tsx
  src/framework/ui/tabNavigator/bottomNavigatorTab.spec.tsx.snap
  src/framework/ui/tabNavigator/bottomTabNavigator.component.tsx
  src/framework/ui/tabNavigator/bottomTabNavigator.spec.tsx
  src/framework/ui/tabNavigator/bottomTabNavigator.spec.tsx.snap
  src/framework/ui/toggle/toggle.component.tsx
  src/framework/ui/tooltip/tooltip.component.tsx
  src/framework/ui/topNavigationBar/topNavigationBar.component.tsx
  src/framework/ui/topNavigationBar/topNavigationBar.spec.config.ts
  src/framework/ui/topNavigationBar/topNavigationBar.spec.tsx
  src/framework/ui/topNavigationBar/topNavigationBar.spec.tsx.snap
  src/framework/ui/topNavigationBar/topNavigationBarAction.component.tsx
  src/framework/ui/viewPager/viewPager.component.tsx
  src/playground/src/ui/screen/button.component.tsx
  src/playground/src/ui/screen/buttonGroup.component.tsx
  src/playground/src/ui/screen/tabNavigator.component.tsx
  src/playground/src/ui/screen/tabView.component.tsx
  src/playground/src/ui/screen/topNavigationBar.component.tsx
Labels: module:ui, next

#295 fix(ui): modal component/service/panel, popover fix. Closes #269
  src/framework/theme/component/modal/modalPanel.component.tsx
  src/framework/theme/component/modal/modalPanel.spec.tsx
  src/framework/theme/component/modal/modalPanel.spec.tsx.snap
  src/framework/theme/service/modal/modal.service.tsx
  src/framework/theme/service/modal/modal.spec.tsx
  src/framework/theme/type.ts
  src/framework/ui/modal/modal.component.tsx
  src/framework/ui/modal/modal.spec.tsx
  src/framework/ui/modal/modal.spec.tsx.snap
  src/framework/ui/popover/popover.component.tsx
  src/framework/ui/popover/popoverView.component.tsx
  src/playground/src/ui/screen/dialog.component.tsx
  src/playground/src/ui/screen/modal.component.tsx
  src/playground/src/ui/screen/popover.component.tsx
  src/playground/src/ui/screen/tooltip.component.tsx
Labels: module:ui, needs review, next

#293 feat(ui): input component. Closes #272
  src/framework/theme/type.ts
  src/framework/ui/index.ts
  src/framework/ui/input/input.component.tsx
  src/framework/ui/input/input.spec.config.ts
  src/framework/ui/input/input.spec.tsx
  src/framework/ui/input/input.spec.tsx.snap
  src/framework/ui/service/type.ts
  src/playground/src/ui/screen/index.ts
  src/playground/src/ui/screen/input.component.tsx
  tslint.json
Labels: module:ui, needs review, next

#304 fix(theme): style provider - reduce setState calls
  src/framework/theme/component/application/applicationProvider.component.tsx
  src/framework/ui/popover/popover.component.tsx
  src/framework/ui/tooltip/tooltip.component.tsx
Labels: bug, module:theme, needs review

#305 feat(ui): avatar component
  src/framework/ui/avatar/avatar.component.tsx
  src/framework/ui/avatar/avatar.spec.config.ts
  src/framework/ui/avatar/avatar.spec.tsx
  src/framework/ui/avatar/avatar.spec.tsx.snap
  src/framework/ui/index.ts
  src/playground/src/ui/screen/avatar.component.tsx
  src/playground/src/ui/screen/index.ts
Labels: module:ui, needs review, next

#303 feat(ui): list component
  src/framework/ui/index.ts
  src/framework/ui/list/list.component.tsx
  src/framework/ui/list/list.spec.config.ts
  src/framework/ui/list/list.spec.tsx
  src/framework/ui/list/list.spec.tsx.snap
  src/framework/ui/list/listItem.component.tsx
  src/playground/src/ui/screen/index.ts
  src/playground/src/ui/screen/list.component.tsx
  src/playground/src/ui/screen/listItem.showcase.component.tsx
Labels: module:ui, needs review, next

#307 feat(ui): radio - add text support
  src/framework/ui/radio/radio.component.tsx
  src/framework/ui/radio/radio.spec.config.ts
  src/framework/ui/radio/radio.spec.tsx.snap
  src/framework/ui/radioGroup/radioGroup.spec.config.ts
  src/playground/src/ui/screen/radio.component.tsx
Labels: module:ui, needs review, next

#306 feat(ui): overflow-menu
  src/framework/ui/index.ts
  src/framework/ui/list/list.spec.tsx
  src/framework/ui/list/listItem.component.tsx
  src/framework/ui/modal/modal.component.tsx
  src/framework/ui/modal/modal.spec.tsx.snap
  src/framework/ui/overflowMenu/overflowMenu.component.tsx
  src/framework/ui/overflowMenu/overflowMenu.spec.config.ts
  src/framework/ui/overflowMenu/overflowMenu.spec.tsx
  src/framework/ui/overflowMenu/overflowMenu.spec.tsx.snap
  src/framework/ui/overflowMenu/overflowMenuItem.component.tsx
  src/framework/ui/popover/popover.component.tsx
  src/framework/ui/service/type.ts
  src/playground/src/ui/screen/index.ts
  src/playground/src/ui/screen/list.component.tsx
  src/playground/src/ui/screen/overflowMenu.component.tsx
Labels: module:ui, needs review, next

#309 feat(ui): checkbox - add text support
  src/framework/ui/checkbox/checkbox.component.tsx
  src/framework/ui/common/checkmark.component.tsx
  src/framework/ui/drawable/checkmark/checkmark.component.tsx
  src/framework/ui/toggle/toggle.component.tsx
  src/framework/ui/toggle/toggle.spec.tsx.snap
  src/playground/src/ui/screen/checkbox.component.tsx
Labels: module:ui, needs review, next

#310 refactor(ui): toggle icon refactor
  src/framework/ui/drawable/checkmark/checkmark.component.tsx
  src/framework/ui/toggle/toggle.component.tsx
  src/framework/ui/toggle/toggle.spec.tsx.snap
  src/playground/src/ui/screen/toggle.component.tsx
Labels: module:ui, needs review, next

#313 refactor(framework): adopt to eva mappings
  src/framework/theme/component/application/application.spec.config.ts
  src/framework/theme/component/style/style.spec.config.ts
  src/framework/theme/service/style/style.spec.config.ts
  src/framework/theme/service/style/styleConsumer.service.ts
  src/framework/ui/avatar/avatar.spec.config.ts
  src/framework/ui/button/button.component.tsx
  src/framework/ui/button/button.spec.config.ts
  src/framework/ui/buttonGroup/buttonGroup.component.tsx
  src/framework/ui/buttonGroup/buttonGroup.spec.config.ts
  src/framework/ui/checkbox/checkbox.component.tsx
  src/framework/ui/checkbox/checkbox.spec.config.ts
  src/framework/ui/index.ts
  src/framework/ui/input/input.component.tsx
  src/framework/ui/input/input.spec.config.ts
  src/framework/ui/layout/layout.spec.config.ts
  src/framework/ui/list/list.spec.config.ts
  src/framework/ui/list/list.spec.tsx.snap
  src/framework/ui/list/listItem.component.tsx
  src/framework/ui/modal/modal.component.tsx
  src/framework/ui/modal/modal.spec.config.ts
  src/framework/ui/modal/modal.spec.tsx
  src/framework/ui/modal/modal.spec.tsx.snap
  src/framework/ui/overflowMenu/overflowMenu.component.tsx
  src/framework/ui/overflowMenu/overflowMenu.spec.config.ts
  src/framework/ui/overflowMenu/overflowMenuItem.component.tsx
  src/framework/ui/radio/radio.component.tsx
  src/framework/ui/radio/radio.spec.config.ts
  src/framework/ui/radioGroup/radioGroup.spec.config.ts
  src/framework/ui/tab/tab.component.tsx
  src/framework/ui/tab/tab.spec.contig.ts
  src/framework/ui/tab/tab.spec.tsx.snap
  src/framework/ui/tab/tabBar.component.tsx
  src/framework/ui/tabNavigator/bottomNavigatorTab.component.tsx
  src/framework/ui/tabNavigator/bottomNavigatorTab.spec.config.ts
  src/framework/ui/tabNavigator/bottomNavigatorTab.spec.tsx.snap
  src/framework/ui/tabNavigator/bottomTabNavigator.component.tsx
  src/framework/ui/tabNavigator/bottomTabNavigator.spec.config.ts
  src/framework/ui/tabNavigator/bottomTabNavigator.spec.tsx.snap
  src/framework/ui/toggle/toggle.component.tsx
  src/framework/ui/toggle/toggle.spec.config.ts
  src/framework/ui/toggle/toggle.spec.tsx.snap
  src/framework/ui/tooltip/tooltip.component.tsx
  src/framework/ui/topNavigationBar/topNavigationBar.component.tsx
  src/framework/ui/topNavigationBar/topNavigationBar.spec.config.ts
  src/framework/ui/topNavigationBar/topNavigationBar.spec.tsx.snap
  src/playground/src/ui/screen/overflowMenu.component.tsx
  src/playground/src/ui/screen/topNavigationBar.component.tsx
Labels: module:ui, needs review, next

#314 fix(ui): popover visibility
  src/framework/ui/overflowMenu/overflowMenu.component.tsx
  src/framework/ui/overflowMenu/overflowMenu.spec.tsx.snap
  src/framework/ui/popover/popover.component.tsx
Labels: module:ui, needs review, next

#315 feat(theme): styles validation
  src/framework/theme/service/style/style.service.ts
  src/framework/theme/service/style/style.spec.config.ts
  src/framework/theme/service/style/style.spec.ts
  src/framework/theme/service/style/styleConsumer.service.ts
  src/framework/ui/buttonGroup/buttonGroup.spec.config.ts
  src/framework/ui/layout/layout.spec.config.ts
Labels: module:theme, needs review, next

#325 build(package): make package prod-compatible
  index.ts
  jest.config.js
  jest.config.snapshot.js
  package.json
  src/framework/theme/component/application/applicationProvider.component.tsx
  src/framework/theme/component/mapping/mapping.spec.tsx
  src/framework/theme/component/mapping/mappingContext.ts
  src/framework/theme/component/mapping/mappingProvider.component.tsx
  src/framework/theme/component/style/styleConsumer.component.tsx
  src/framework/theme/index.ts
  src/framework/theme/service/style/style.service.ts
  src/framework/theme/service/style/style.spec.ts
  src/framework/theme/service/style/styleConsumer.service.ts
  src/framework/ui/package.json
  src/framework/ui/tab/tab.component.tsx
  src/framework/ui/text/text.component.tsx
  src/playground/app.json
  src/playground/metro.config.js
  src/playground/package.json
  src/playground/src/app.component.tsx
  src/playground/src/ui/screen/avatar.component.tsx
  src/playground/src/ui/screen/bottomNavigation.component.tsx
  src/playground/src/ui/screen/button.component.tsx
  src/playground/src/ui/screen/buttonGroup.component.tsx
  src/playground/src/ui/screen/checkbox.component.tsx
  src/playground/src/ui/screen/dialog.component.tsx
  src/playground/src/ui/screen/home.component.tsx
  src/playground/src/ui/screen/index.ts
  src/playground/src/ui/screen/input.component.tsx
  src/playground/src/ui/screen/layout.component.tsx
  src/playground/src/ui/screen/list.component.tsx
  src/playground/src/ui/screen/modal.component.tsx
  src/playground/src/ui/screen/overflowMenu.component.tsx
  src/playground/src/ui/screen/popover.component.tsx
  src/playground/src/ui/screen/radio.component.tsx
  src/playground/src/ui/screen/radioGroup.component.tsx
  src/playground/src/ui/screen/tabBar.component.tsx
  src/playground/src/ui/screen/tabView.component.tsx
  src/playground/src/ui/screen/text.component.tsx
  src/playground/src/ui/screen/toggle.component.tsx
  src/playground/src/ui/screen/tooltip.component.tsx
  src/playground/src/ui/screen/topNavigationBar.component.tsx
  src/playground/src/ui/screen/viewPager.component.tsx
  src/playground/src/ui/styles.ts
  tsconfig.jest.json
Labels: module:playground, module:ui, needs review, next
