Repository akveo/react-native-ui-kitten, pull requests merged in 2019-02, with the labels that each got.

#245 feat(framework): modal service
  src/framework/theme/component/application/application.spec.config.ts
  src/framework/theme/component/application/application.spec.tsx
  src/framework/theme/component/application/application.spec.tsx.snap
  src/framework/theme/component/application/applicationProvider.component.tsx
  src/framework/theme/component/application/index.ts
  src/framework/theme/component/index.ts
  src/framework/theme/component/modal/index.ts
  src/framework/theme/component/modal/modal.component.tsx
  src/framework/theme/component/modal/modal.spec.tsx
  src/framework/theme/component/modal/modal.spec.tsx.snap
  src/framework/theme/component/modal/modalPanel.component.tsx
  src/framework/theme/component/style/styleProvider.component.tsx
  src/framework/theme/index.ts
  src/framework/theme/service/index.ts
  src/framework/theme/service/modal/index.ts
  src/framework/theme/service/modal/modal.service.tsx
  src/framework/theme/service/modal/modal.spec.tsx
  src/framework/theme/service/modal/modal.spec.tsx.snap
  src/framework/theme/type.ts
  src/playground/src/app.component.tsx
  src/playground/src/ui/screen/dialog.component.tsx
  src/playground/src/ui/screen/index.ts
Labels: needs review, next

#264 feat/refactor(ui): modal component "backdrop" fix, animations add, tests update
  src/framework/theme/component/modal/index.ts
  src/framework/theme/component/modal/modal.component.tsx
  src/framework/theme/component/modal/modal.spec.tsx
  src/framework/theme/component/modal/modal.spec.tsx.snap
  src/framework/theme/component/modal/modalPanel.component.tsx
  src/framework/theme/component/modal/modalPanel.spec.tsx
  src/framework/theme/component/modal/modalPanel.spec.tsx.snap
  src/framework/theme/service/modal/modal.service.tsx
  src/framework/theme/service/modal/modal.spec.tsx
  src/framework/theme/service/modal/modal.spec.tsx.snap
  src/framework/ui/index.ts
  src/framework/ui/modal/modal.component.tsx
  src/framework/ui/modal/modal.spec.config.ts
  src/framework/ui/modal/modal.spec.tsx
  src/framework/ui/modal/modal.spec.tsx.snap
  src/playground/package-lock.json
  src/playground/src/app.component.tsx
  src/playground/src/ui/screen/dialog.component.tsx
  src/playground/src/ui/screen/index.ts
  src/playground/src/ui/screen/modal.component.tsx
Labels: module:theme, module:ui, next

#262 feat(ui): top navigation bar component
  src/framework/ui/index.ts
  src/framework/ui/topNavigationBar/topNavigationBar.component.tsx
  src/framework/ui/topNavigationBar/topNavigationBar.spec.config.ts
  src/framework/ui/topNavigationBar/topNavigationBar.spec.tsx
  src/framework/ui/topNavigationBar/topNavigationBar.spec.tsx.snap
  src/framework/ui/topNavigationBar/topNavigationBarAction.component.tsx
  src/playground/src/ui/screen/index.ts
  src/playground/src/ui/screen/topNavigationBar.component.tsx
Labels: module:ui, next

#254 feat(ui): bottom tab navigator(react navigation)
  package-lock.json
  src/framework/ui/index.ts
  src/framework/ui/tabNavigator/bottomNavigatorTab.component.tsx
  src/framework/ui/tabNavigator/bottomNavigatorTab.spec.config.ts
  src/framework/ui/tabNavigator/bottomNavigatorTab.spec.tsx
  src/framework/ui/tabNavigator/bottomNavigatorTab.spec.tsx.snap
  src/framework/ui/tabNavigator/bottomTabNavigator.component.tsx
  src/framework/ui/tabNavigator/bottomTabNavigator.spec.config.ts
  src/framework/ui/tabNavigator/bottomTabNavigator.spec.tsx
  src/framework/ui/tabNavigator/bottomTabNavigator.spec.tsx.snap
  src/playground/package-lock.json
  src/playground/src/ui/screen/index.ts
  src/playground/src/ui/screen/tabNavigator.component.tsx
Labels: module:ui, next

#247 refactor(framework): apply code style and token-groups
  src/framework/theme/component/mapping/mappingContext.ts
  src/framework/theme/component/mapping/mappingProvider.component.tsx
  src/framework/theme/component/style/styleConsumer.component.tsx
  src/framework/theme/component/style/styleProvider.component.tsx
  src/framework/theme/component/theme/themeConsumer.component.tsx
  src/framework/theme/component/theme/themeContext.ts
  src/framework/theme/component/theme/themeProvider.component.tsx
  src/framework/theme/service/style/style.service.ts
  src/framework/theme/service/style/styleConsumer.service.ts
  src/framework/theme/service/theme/theme.service.ts
  src/framework/theme/type.ts
  src/framework/ui/checkbox/checkbox.component.tsx
  src/framework/ui/layout/layout.component.tsx
  src/framework/ui/layout/layout.spec.tsx.snap
  src/framework/ui/modal/modal.component.tsx
  src/framework/ui/modal/modal.spec.tsx.snap
  src/framework/ui/radio/radio.component.tsx
  src/framework/ui/radio/radio.spec.config.ts
  src/framework/ui/radio/radio.spec.tsx
  src/framework/ui/radioGroup/radioGroup.component.tsx
  src/framework/ui/radioGroup/radioGroup.spec.tsx
  src/framework/ui/service/common.service.ts
  src/framework/ui/tab/tab.component.tsx
  src/framework/ui/tab/tab.spec.tsx
  src/framework/ui/tab/tab.spec.tsx.snap
  src/framework/ui/tab/tabBar.component.tsx
  src/framework/ui/tab/tabBarIndicator.component.tsx
  src/framework/ui/tab/tabView.component.tsx
  src/framework/ui/tabNavigator/bottomNavigatorTab.component.tsx
  src/framework/ui/tabNavigator/bottomNavigatorTab.spec.tsx
  src/framework/ui/tabNavigator/bottomNavigatorTab.spec.tsx.snap
  src/framework/ui/tabNavigator/bottomTabNavigator.component.tsx
  src/framework/ui/tabNavigator/bottomTabNavigator.spec.tsx
  src/framework/ui/tabNavigator/bottomTabNavigator.spec.tsx.snap
  src/framework/ui/toggle/toggle.component.tsx
  src/framework/ui/topNavigationBar/topNavigationBar.component.tsx
  src/framework/ui/topNavigationBar/topNavigationBar.spec.tsx.snap
  src/framework/ui/viewPager/viewPager.component.tsx
  src/playground/src/app.component.tsx
  src/playground/src/ui/screen/dialog.component.tsx
  src/playground/src/ui/screen/layout.component.tsx
  src/playground/src/ui/screen/modal.component.tsx
  src/playground/src/ui/screen/radio.component.tsx
  src/playground/src/ui/screen/tabNavigator.component.tsx
  src/playground/src/ui/screen/toggle.component.tsx
Labels: module:theme, module:ui, needs review

#265 feat(ui): text component
  src/framework/ui/index.ts
  src/framework/ui/text/text.component.tsx
  src/playground/src/ui/screen/index.ts
  src/playground/src/ui/screen/text.component.tsx
Labels: module:ui, needs review, next

#270 fix(ci): travis auth
  .travis.yml
  travis_deploy_key.enc
Labels: module:build, needs review, next

#268 feat(ui): button component. Closes #260
  src/framework/ui/button/button.component.tsx
  src/framework/ui/button/button.spec.config.ts
  src/framework/ui/button/button.spec.tsx
  src/framework/ui/button/button.spec.tsx.snap
  src/framework/ui/button/type.ts
  src/framework/ui/index.ts
  src/playground/metro.config.js
  src/playground/src/ui/screen/button.component.tsx
  src/playground/src/ui/screen/dialog.component.tsx
  src/playground/src/ui/screen/index.ts
Labels: module:ui, needs review, next

#263 feat(ui): tooltip component. Closes #261
  package-lock.json
  src/framework/ui/drawable/arrow/arrow.component.tsx
  src/framework/ui/index.ts
  src/framework/ui/modal/modal.component.tsx
  src/framework/ui/modal/modal.spec.tsx.snap
  src/framework/ui/popover/measure.component.tsx
  src/framework/ui/popover/popover.component.tsx
  src/framework/ui/popover/popoverView.component.tsx
  src/framework/ui/popover/type.spec.ts
  src/framework/ui/popover/type.ts
  src/framework/ui/radio/radio.spec.tsx.snap
  src/framework/ui/service/type.ts
  src/framework/ui/tooltip/tooltip.component.tsx
  src/playground/src/ui/screen/index.ts
  src/playground/src/ui/screen/popover.component.tsx
  src/playground/src/ui/screen/tooltip.component.tsx
Labels: module:ui, needs review, next

#230 rkChoice onChange #229
  src/components/choice/rkChoice.js
Labels: needs review
