Repository akveo/react-native-ui-kitten, pull requests merged in 2019-06, with the labels that each got.

#411 refactor(ui): radio/checkbox mapping refactor
  package-lock.json
  src/framework/ui/radio/radio.spec.tsx.snap
  src/framework/ui/support/tests/mapping.json
  src/playground/package-lock.json
Labels: module:ui, needs review, next

#410 fix(theme): style HOCs component arg type
  src/framework/theme/style/styleConsumer.component.tsx
  src/framework/theme/theme/themeConsumer.component.tsx
Labels: module:build, module:theme, next

#413 refactor(mapping/theme): theme variables refactor
  src/framework/ui/button/button.component.tsx
  src/framework/ui/input/input.component.tsx
  src/framework/ui/radio/radio.spec.tsx.snap
  src/framework/ui/support/tests/mapping.json
  src/framework/ui/support/tests/theme.json
  src/framework/ui/text/text.component.tsx
  src/playground/package-lock.json
  src/playground/src/ui/screen/buttonGroup/type.ts
  src/playground/src/ui/screen/checkbox/type.ts
  src/playground/src/ui/screen/common/showcase.component.tsx
  src/playground/src/ui/screen/common/showcaseSettings.component.tsx
  src/playground/src/ui/screen/input/type.tsx
  src/playground/src/ui/screen/modal/modalShowcase.component.tsx
Labels: module:playground, module:ui, needs review, next

#416 build(common): update eva dependencies
  package-lock.json
  package.json
  src/playground/package-lock.json
  src/playground/package.json
  src/playground/src/ui/screen/common/showcase.component.tsx
Labels: module:build, next

#421 feat(common): release pipeline add
  CHANGELOG.md
  package-lock.json
  package.json
  scripts/publish/publish.sh
  src/framework/tsconfig.json
  src/playground/tsconfig.json
  tsconfig.json
Labels: module:build, needs review, next

#420 refactor(script): travis-ci scripts
  .travis.yml
  package.json
Labels: module:build, next

#422 fix(ui): view-pager scroll event on android
  src/framework/ui/viewPager/viewPager.component.tsx
Labels: module:ui, next

#423 fix(ui): button-group dividers
  src/framework/ui/buttonGroup/buttonGroup.component.tsx
Labels: module:ui, next

#424 build(common): update expo to sdk-33
  jest.config.js
  package-lock.json
  package.json
  scripts/build/compile-ts.sh
  scripts/build/transform-paths.sh
  scripts/environment/set-env.sh
  scripts/gulp/tasks/docs/example.ts
  scripts/publish/publish.sh
  src/framework/index.ts
  src/framework/package.json
  src/framework/tsconfig.json
  src/framework/ui/support/services/validation.spec.ts
  src/playground/app.json
  src/playground/metro.config.js
  src/playground/package-lock.json
  src/playground/package.json
  src/playground/src/ui/screen/text/type.ts
  src/playground/tsconfig.json
  tsconfig.dev.json
  tsconfig.jest.json
  tsconfig.prod.json
  tsconfig.test.json
Labels: module:build, next

#426 docs(common): fix DEV_DOCS, CODE_OF_CONDUCT, CONTRIBUTING
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  DEV_DOCS.md
Labels: module:docs, needs review, next

#428 docs(readme): update README.md
  README.md
Labels: module:docs, next

#430 build(common): bump eva version to 1.0.0
  package-lock.json
  package.json
  src/framework/package.json
  src/playground/package-lock.json
  src/playground/package.json
Labels: module:build, next

#431 refactor(docs): common issues refactor
  docs/src/app/blocks/components/pager-block/pager-block.component.scss
  docs/src/app/documentation/page/page.component.ts
  docs/src/structure.ts
  src/framework/ui/layout/layout.component.tsx
Labels: module:docs, needs review, next

#385 release: v3.1.4
  CHANGELOG.md
  package.json
  src/components/calendar/cells/rkCalendarDay.component.js
  src/components/calendar/cells/rkCalendarMonth.component.js
  src/components/calendar/cells/rkCalendarWeek.component.js
  src/components/calendar/cells/rkCalendarYear.component.js
  src/components/calendar/common/rkCalendarDaysNames.component.js
  src/components/calendar/common/rkCalendarMonthHeader.component.js
  src/components/calendar/common/rkCalendarMonthName.component.js
  src/components/calendar/common/rkCalendarView.component.js
  src/components/calendar/layout/index.js
  src/components/calendar/layout/rkCalendarHorizontalLayout.js
  src/components/calendar/layout/rkCalendarVerticalLayout.js
  src/components/calendar/rkCalendar.component.js
  src/components/calendar/services/index.js
  src/components/calendar/strategy/baseCalendarSelectionStrategy.js
  src/components/calendar/strategy/index.js
  src/components/calendar/strategy/rangedCalendarSelectionStrategy.js
  src/components/choice/rkChoice.js
  src/components/choiceGroup/rkChoiceGroup.js
  src/components/tabset/rkTab.component.js
  src/components/tabset/rkTabBar.component.js
  src/components/tabset/rkTabBarIndicator.component.js
  src/components/tabset/rkTabPager.component.js
Labels: needs review

#445 fix(top-navigation): add hit-slop to actions
  src/framework/ui/topNavigation/topNavigationAction.component.tsx
Labels: module:ui

#447 fix(docs): theme import typo
  README.md
  docs/src/guides/theme-switching.md
  docs/src/guides/theme-system.md
  docs/src/guides/theme-using-mapping.md
  src/framework/theme/application/applicationProvider.component.tsx
Labels: module:docs

#454 docs(dev): update DEV_DOCS.md
  DEV_DOCS.md
Labels: module:docs

#461 docs(guides): add design system guides
  README.md
  docs/src/app/@theme/services/structure.service.ts
  docs/src/articles/design-system/custom-mapping.md
  docs/src/articles/design-system/custom-theme.md
  docs/src/articles/design-system/customize-mapping.md
  docs/src/articles/design-system/customize-theme.md
  docs/src/articles/design-system/glossary.md
  docs/src/articles/design-system/intro.md
  docs/src/articles/design-system/theme-change.md
  docs/src/articles/design-system/theme.md
  docs/src/articles/design-system/use-theme-variables.md
  docs/src/articles/getting-started/what-is-ui-kitten.md
  docs/src/articles/getting-started/where-to-start.md
  docs/src/articles/guides/create-screen.md
  docs/src/articles/guides/install.md
  docs/src/assets/images/articles/design-system/aquamarine-theme.png
  docs/src/assets/images/articles/design-system/custom-mapping-initial.png
  docs/src/assets/images/articles/design-system/custom-mapping-state.gif
  docs/src/assets/images/articles/design-system/custom-mapping-variant.png
  docs/src/assets/images/articles/design-system/customize-mapping.png
  docs/src/assets/images/articles/guides/sample-screen.png
  docs/src/assets/images/articles/sample-page.png
  docs/src/guides/index.md
  docs/src/guides/install-into-existing.md
  docs/src/guides/theme-customize-component.md
  docs/src/guides/theme-switching.md
  docs/src/guides/theme-system.md
  docs/src/guides/theme-using-mapping.md
  docs/src/guides/theme-using-variables.md
  docs/src/structure.ts
  package-lock.json
  src/playground/package-lock.json
Labels: module:docs

#468 Update toggle component doc and example
  src/framework/ui/toggle/toggle.component.tsx
Labels: module:docs

#471 feat(ui): add custom warnings for incorrect component usage
  src/framework/theme/style/styleConsumer.service.ts
Labels: enhancement, module:ui

#470 build: fix typescript build errors
  package-lock.json
  package.json
  src/framework/ui/support/typings/type.ts
  src/playground/package-lock.json
  src/playground/package.json
Labels: module:build

#475 build(common): typescript common issues
  jest.config.js
  tsconfig.dev.json
  tsconfig.json
  tsconfig.prod.json
  tsconfig.test.json
Labels: module:build

#478 fix(docs): toggle docs fix
  src/framework/ui/toggle/toggle.component.tsx
Labels: module:docs

#484 fix(ui): checkbox usage docs
  src/framework/ui/checkbox/checkbox.component.tsx
Labels: module:docs

#483 fix(ui): add input api methods
  src/framework/ui/input/input.component.tsx
  src/framework/ui/input/input.spec.tsx
Labels: enhancement, module:ui

#486 docs(readme): update design system link
  README.md
Labels: module:docs
