Repository akveo/react-native-ui-kitten, pull requests merged in 2019-09, with the labels that each got.

#608 fix(ui): select - selectedOption value change
  src/framework/ui/select/select.component.tsx
  src/framework/ui/select/selection.strategy.ts
Labels: module:ui, needs review

#610 refactor(ui): modal - backdrop style prop definition
  src/framework/ui/modal/modal.component.tsx
Labels: module:build, module:ui

#626 feat(ui): top-navigation - control appearance
  src/framework/ui/topNavigation/topNavigation.component.tsx
  src/playground/src/ui/screen/topNavigation/type.tsx
Labels: module:ui, needs review

#627 refactor(ui): text - allow text element in children
  src/framework/ui/text/text.component.tsx
Labels: module:ui, needs review

#630 fix(ui): tab-view - tab content size
  src/framework/ui/tab/tabView.component.tsx
Labels: module:ui, needs review

#636 Fix/bottom nav docs
  src/framework/ui/bottomNavigation/bottomNavigation.component.tsx
Labels: module:docs

#639 docs(components): update drawer documentation
  docs/src/structure.ts
  scripts/gulp/tasks/docs/docs.ts
  src/framework/ui/drawer/drawer.component.tsx
  src/framework/ui/drawer/drawerHeaderFooter.component.tsx
Labels: module:docs, module:ui, needs review

#638 feat(ui): animation-config property to Icon component add
  src/framework/ui/icon/icon.component.tsx
  src/framework/ui/icon/iconAnimation.ts
  src/framework/ui/index.ts
  src/playground/src/ui/screen/icon/type.ts
Labels: module:docs, module:ui

#628 feat(ui): toggle - add text property
  src/framework/ui/toggle/toggle.component.tsx
  src/framework/ui/toggle/toggle.spec.tsx
  src/framework/ui/toggle/toggle.spec.tsx.snap
  src/playground/src/ui/screen/toggle/type.ts
Labels: module:ui, needs review

#642 docs(components): refactor examples with js code and framework icon c…
  docs/src/articles/guides/create-screen.md
  docs/src/articles/guides/install-existing.md
  docs/src/articles/guides/setup-icons-module.md
  docs/src/articles/guides/setup-vector-icons.md
  docs/src/structure.ts
  src/framework/theme/application/applicationProvider.component.tsx
  src/framework/theme/modal/modal.service.tsx
  src/framework/theme/style/styleConsumer.component.tsx
  src/framework/theme/theme/themeConsumer.component.tsx
  src/framework/ui/avatar/avatar.component.tsx
  src/framework/ui/bottomNavigation/bottomNavigation.component.tsx
  src/framework/ui/bottomNavigation/bottomNavigationTab.component.tsx
  src/framework/ui/button/button.component.tsx
  src/framework/ui/buttonGroup/buttonGroup.component.tsx
  src/framework/ui/checkbox/checkbox.component.tsx
  src/framework/ui/drawer/drawer.component.tsx
  src/framework/ui/drawer/drawerHeaderFooter.component.tsx
  src/framework/ui/icon/icon.component.tsx
  src/framework/ui/icon/iconRegistry.component.tsx
  src/framework/ui/input/input.component.tsx
  src/framework/ui/layout/layout.component.tsx
  src/framework/ui/list/list.component.tsx
  src/framework/ui/list/listItem.component.tsx
  src/framework/ui/menu/menu.component.tsx
  src/framework/ui/modal/modal.component.tsx
  src/framework/ui/overflowMenu/overflowMenu.component.tsx
  src/framework/ui/popover/popover.component.tsx
  src/framework/ui/radio/radio.component.tsx
  src/framework/ui/radioGroup/radioGroup.component.tsx
  src/framework/ui/select/select.component.tsx
  src/framework/ui/spinner/spinner.component.tsx
  src/framework/ui/tab/tab.component.tsx
  src/framework/ui/tab/tabBar.component.tsx
  src/framework/ui/tab/tabView.component.tsx
  src/framework/ui/text/text.component.tsx
  src/framework/ui/toggle/toggle.component.tsx
  src/framework/ui/tooltip/tooltip.component.tsx
  src/framework/ui/topNavigation/topNavigation.component.tsx
  src/framework/ui/topNavigation/topNavigationAction.component.tsx
  src/framework/ui/viewPager/viewPager.component.tsx
Labels: module:docs, module:ui, needs review

#631 feat(ui): add font-family for each component that has text
  src/framework/ui/bottomNavigation/bottomNavigationTab.component.tsx
  src/framework/ui/button/button.component.tsx
  src/framework/ui/checkbox/checkbox.component.tsx
  src/framework/ui/input/input.component.tsx
  src/framework/ui/list/listItem.component.tsx
  src/framework/ui/menu/menuItem.component.tsx
  src/framework/ui/radio/radio.component.tsx
  src/framework/ui/select/select.component.tsx
  src/framework/ui/select/selectOption.component.tsx
  src/framework/ui/tab/tab.component.tsx
  src/framework/ui/tooltip/tooltip.component.tsx
  src/framework/ui/topNavigation/topNavigation.component.tsx
Labels: module:ui, needs review

#646 refactor(script): set-env script with node
  package.json
  scripts/environment/set-env.js
  scripts/environment/set-env.sh
Labels: needs review

#647 docs(components): add top-navigation with menu example
  src/framework/ui/topNavigation/topNavigation.component.tsx
Labels: module:docs, module:ui, needs review

#635 feat(ui): eva 1.2 mappings and documentation adopt
  src/framework/ui/button/button.component.tsx
  src/framework/ui/checkbox/checkbox.component.tsx
  src/framework/ui/icon/icon.component.tsx
  src/framework/ui/radio/radio.component.tsx
  src/framework/ui/radio/radio.spec.tsx.snap
  src/framework/ui/support/tests/mapping.json
  src/framework/ui/support/tests/theme.json
  src/framework/ui/toggle/toggle.component.tsx
  src/playground/package-lock.json
  src/playground/src/ui/screen/button/type.tsx
  src/playground/src/ui/screen/buttonGroup/type.ts
  src/playground/src/ui/screen/checkbox/type.ts
  src/playground/src/ui/screen/home.component.tsx
  src/playground/src/ui/screen/radio/type.ts
  src/playground/src/ui/screen/toggle/type.ts
Labels: module:docs, module:ui

#651 fix(script): template modules publish script
  scripts/publish/publish-modules.sh
  src/templates/template-ui-kitten-typescript/package-lock.json
  src/templates/template-ui-kitten-typescript/package.json
  src/templates/template-ui-kitten/package-lock.json
  src/templates/template-ui-kitten/package.json
  tsconfig.prod.json
Labels: module:build, module:cli-template
