Repository akveo/react-native-ui-kitten, pull requests merged in 2019-11, with the labels that each got.

#707 fix(ui): modal center positioning
  src/framework/ui/modal/modal.component.tsx
Labels: module:ui, needs review, web

#708 feat(ui): card component add
  docs/src/structure.ts
  package-lock.json
  src/framework/ui/card/card.component.tsx
  src/framework/ui/card/card.spec.tsx
  src/framework/ui/card/cardHeader.component.tsx
  src/framework/ui/index.ts
  src/framework/ui/support/tests/mapping.json
  src/playground/package-lock.json
  src/playground/src/navigation/navigation.component.tsx
  src/playground/src/ui/screen/card/card.container.tsx
  src/playground/src/ui/screen/card/cardExamples.tsx
  src/playground/src/ui/screen/card/cardShowcase.component.tsx
  src/playground/src/ui/screen/card/type.tsx
  src/playground/src/ui/screen/home.component.tsx
  src/playground/src/ui/screen/index.ts
  src/playground/src/ui/screen/showcases/card/cardCustomHeader.component.tsx
  src/playground/src/ui/screen/showcases/card/cardEvaHeader.component.tsx
  src/playground/src/ui/screen/showcases/card/cardFooter.component.tsx
  src/playground/src/ui/screen/showcases/card/cardHeaderFooter.component.tsx
  src/playground/src/ui/screen/showcases/card/cardSimpleUsage.component.tsx
  src/playground/src/ui/screen/showcases/card/cardStatuses.component.tsx
  src/playground/src/ui/screen/showcases/card/index.ts
Labels: module:ui, needs review

#706 docs(components): refactor component base props api
  src/framework/ui/avatar/avatar.component.tsx
  src/framework/ui/bottomNavigation/bottomNavigation.component.tsx
  src/framework/ui/bottomNavigation/bottomNavigationTab.component.tsx
  src/framework/ui/button/button.component.tsx
  src/framework/ui/buttonGroup/buttonGroup.component.tsx
  src/framework/ui/calendar/calendar.component.tsx
  src/framework/ui/calendar/rangeCalendar.component.tsx
  src/framework/ui/checkbox/checkbox.component.tsx
  src/framework/ui/divider/divider.component.tsx
  src/framework/ui/drawer/drawer.component.tsx
  src/framework/ui/drawer/drawerHeaderFooter.component.tsx
  src/framework/ui/input/input.component.tsx
  src/framework/ui/layout/layout.component.tsx
  src/framework/ui/list/list.component.tsx
  src/framework/ui/list/listItem.component.tsx
  src/framework/ui/menu/menu.component.tsx
  src/framework/ui/menu/menuItem.component.tsx
  src/framework/ui/overflowMenu/overflowMenu.component.tsx
  src/framework/ui/popover/popover.component.tsx
  src/framework/ui/radio/radio.component.tsx
  src/framework/ui/radioGroup/radioGroup.component.tsx
  src/framework/ui/select/select.component.tsx
  src/framework/ui/tab/tab.component.tsx
  src/framework/ui/tab/tabBar.component.tsx
  src/framework/ui/tab/tabView.component.tsx
  src/framework/ui/text/text.component.tsx
  src/framework/ui/toggle/toggle.component.tsx
  src/framework/ui/tooltip/tooltip.component.tsx
  src/framework/ui/topNavigation/topNavigation.component.tsx
  src/framework/ui/topNavigation/topNavigationAction.component.tsx
  src/framework/ui/viewPager/viewPager.component.tsx
Labels: module:docs, needs review

#725 fix(ui): list - add ability to override keyExtractor
  src/framework/ui/list/list.component.tsx
Labels: module:ui, needs review

#730 fix(ui): calendar - replace UTC dates with regular dates
  src/framework/ui/calendar/calendar.spec.tsx
  src/framework/ui/calendar/rangeCalendar.spec.tsx
  src/framework/ui/calendar/service/nativeDate.service.spec.ts
  src/framework/ui/calendar/service/nativeDate.service.ts
  src/framework/ui/calendar/service/rangeDate.service.spec.ts
Labels: module:ui, needs review

#727 feat(ui): datepicker - add placeholder property
  src/framework/ui/calendar/baseCalendar.component.tsx
  src/framework/ui/calendar/calendar.component.tsx
  src/framework/ui/calendar/rangeCalendar.component.tsx
  src/framework/ui/datepicker/baseDatepicker.component.tsx
  src/framework/ui/datepicker/datepicker.component.tsx
  src/framework/ui/datepicker/datepicker.spec.tsx
  src/framework/ui/datepicker/rangeDatepicker.component.tsx
  src/framework/ui/datepicker/rangeDatepicker.spec.tsx
  src/framework/ui/index.ts
  src/framework/ui/input/input.component.tsx
  src/playground/src/ui/screen/datepicker/datepicker.container.tsx
  src/playground/src/ui/screen/datepicker/datepickerShowcase.component.tsx
  src/playground/src/ui/screen/datepicker/rangeDatepickerShowcase.component.tsx
Labels: module:ui, needs review

#705 refactor(playground): use opensans as default font
  src/playground/App.tsx
  src/playground/app.json
  src/playground/assets/splash.png
  src/playground/package.json
  src/playground/src/app/app.component.tsx
  src/playground/src/app/applicationLoader.component.tsx
  src/playground/src/app/loadingAnimation.component.tsx
  src/playground/src/assets/fonts/opensans-bold.ttf
  src/playground/src/assets/fonts/opensans-regular.ttf
  src/playground/src/assets/fonts/opensans-semibold.ttf
  src/playground/src/assets/images/brand-logo.png
  src/playground/src/assets/images/icon.png
  src/playground/src/assets/images/splash.png
  src/playground/src/ui/screen/sample/sample.container.tsx
Labels: module:playground, needs review

#732 refactor(ui): unify icon prop stylings
  src/framework/ui/datepicker/baseDatepicker.component.tsx
  src/framework/ui/menu/menuItem.component.tsx
  src/framework/ui/select/select.component.tsx
  src/framework/ui/topNavigation/topNavigationAction.component.tsx
Labels: module:ui, needs review
